"use client";

import { useEffect, useMemo, useState } from "react";

type ModuleId = "air" | "belt" | "flat" | "chain" | "bucket" | "screw";
type Lang = "th" | "en";
type NumericFields = Record<string, number>;
type Bi = [th: string, en: string];
type Field = { key: string; label: Bi; unit: string; step?: number; options?: number[] };
interface InstallPromptEvent extends Event { prompt: () => Promise<void>; userChoice: Promise<{ outcome: "accepted" | "dismissed" }> }
const tr = (text: Bi, lang: Lang) => text[lang === "th" ? 0 : 1];

const modules: Array<{ id: ModuleId; label: Bi; short: Bi; symbol: string }> = [
  { id: "air", label: ["กระบอกลม", "Air Cylinder"], short: ["ระบบนิวเมติก", "Pneumatic"], symbol: "◎" },
  { id: "belt", label: ["สายพานลำเลียง", "Belt Conveyor"], short: ["วัสดุเทกอง", "Bulk handling"], symbol: "⌁" },
  { id: "flat", label: ["สายพานเรียบ", "Flat Belt"], short: ["ลำเลียงกระสอบ", "Bag transport"], symbol: "▱" },
  { id: "chain", label: ["โซ่ลำเลียง", "Chain Conveyor"], short: ["ลำเลียงชิ้นงาน", "Unit handling"], symbol: "◇" },
  { id: "bucket", label: ["บักเก็ตเอลลิเวเตอร์", "Bucket Elevator"], short: ["ลำเลียงแนวดิ่ง", "Vertical lift"], symbol: "↟" },
  { id: "screw", label: ["สกรูลำเลียง", "Screw Conveyor"], short: ["ป้อนวัสดุ", "Metered flow"], symbol: "≈" },
];

const defaults: Record<ModuleId, NumericFields> = {
  air: { bore: 20, rod: 8, flow: 10, pressure: 4 },
  belt: { capacity: 50, density: 2.16, selectedWidth: 500, materialAngle: 35, troughAngle: 35, slopeCoefficient: 0.85, speed: 1.055, carryIdler: 16, returnIdler: 11.4, carryPitch: 1.2, returnPitch: 3, length: 98, coefficient: 1.8, friction: 0.02, gravity: 9.81, efficiency: 0.8 },
  flat: { length: 7000, angle: 30, throughput: 800, bagLength: 1000, gap: 0, bagWeight: 25, pulleyDiameter: 165, friction: 0.05, gearEfficiency: 0.9, startupFactor: 1.5, serviceFactor: 1.2, motorRpm: 1450, driveTeeth: 15, drivenTeeth: 45, gearboxRatio: 18.79 },
  chain: { load: 200, length: 8, speed: 20, friction: 0.21, efficiency: 0.8, movingMass: 4.16, speedFactor: 1, allowance: 5800, sprocketDiameter: 139.9, motorFactor: 1.1, loadFactor: 1.25 },
  bucket: { capacity: 12, density: 0.45, bucketVolume: 0.0101, pitch: 150, speed: 15, height: 45, bucketWeight: 7.7, chainWeight: 6.56, stands: 2, tempFactor: 7, operationFactor: 1.2, averageStrength: 113, efficiency: 0.8 },
  screw: { screwDiameter: 0.08, shaftDiameter: 0.04, pitch: 0.05, rpm: 1.5, filling: 0.8, incline: 1, density: 0.6, length: 1, friction: 4.4, height: 0, efficiency: 0.6, pipeOD: 40, pipeThickness: 20, pipeLength: 1000, elasticModulus: 210000 },
};

const f = (key: string, th: string, en: string, unit: string, step?: number): Field => ({ key, label: [th, en], unit, step });
const standardBeltWidths = [300, 400, 500, 600, 650, 750, 800, 900, 1000, 1050, 1200, 1350, 1400, 1500, 1600, 1800, 2000, 2200, 2400];
const fieldConfig: Record<ModuleId, Field[]> = {
  air: [f("bore", "ขนาดกระบอก", "Bore size", "mm"), f("rod", "ขนาดก้าน", "Rod size", "mm"), f("flow", "อัตราการไหล", "Air flow", "L/min", .1), f("pressure", "แรงดัน", "Pressure", "bar", .1)],
  belt: [f("capacity", "กำลังลำเลียง", "Capacity", "t/h"), f("density", "ความหนาแน่นวัสดุ", "Material density", "t/m³", .01), { key: "selectedWidth", label: ["ความกว้างสายพานที่เลือก", "Selected belt width"], unit: "mm", options: standardBeltWidths }, f("materialAngle", "มุมกองวัสดุ", "Material angle", "deg"), f("troughAngle", "มุมราง", "Trough angle", "deg"), f("slopeCoefficient", "ตัวคูณความลาด", "Slope coefficient", "k", .01), f("speed", "ความเร็วสายพาน", "Belt speed", "m/s", .001), f("carryIdler", "มวลลูกกลิ้งขาไป", "Carry idler mass", "kg/set", .1), f("returnIdler", "มวลลูกกลิ้งขากลับ", "Return idler mass", "kg/set", .1), f("carryPitch", "พิทช์ลูกกลิ้งขาไป", "Carry idler pitch", "m", .1), f("returnPitch", "พิทช์ลูกกลิ้งขากลับ", "Return idler pitch", "m", .1), f("length", "ความยาวสายพาน", "Conveyor length", "m", .1), f("coefficient", "สัมประสิทธิ์ความต้านทาน", "Resistance coefficient", "C", .1), f("friction", "แรงเสียดทานลูกกลิ้ง", "Idler friction", "f", .001), f("efficiency", "ประสิทธิภาพชุดขับ", "Drive efficiency", "η", .01)],
  flat: [f("length", "ความยาวสายพาน", "Belt length", "mm"), f("angle", "มุมเอียง", "Incline angle", "deg", .1), f("throughput", "อัตราการผลิต", "Production rate", "bags/h"), f("bagLength", "ความยาวกระสอบ", "Bag length", "mm"), f("gap", "ระยะห่างกระสอบ", "Bag spacing", "mm"), f("bagWeight", "น้ำหนักต่อกระสอบ", "Bag weight", "kg", .1), f("pulleyDiameter", "เส้นผ่านศูนย์กลางพูลเลย์", "Pulley diameter", "mm", .1), f("friction", "สัมประสิทธิ์แรงเสียดทาน", "Friction coefficient", "μ", .01), f("motorRpm", "รอบมอเตอร์", "Motor speed", "rpm"), f("gearboxRatio", "อัตราทดเกียร์ที่เลือก", "Selected gearbox ratio", ":1", .01), f("driveTeeth", "จำนวนฟันเฟืองขับ", "Drive sprocket teeth", "T"), f("drivenTeeth", "จำนวนฟันเฟืองตาม", "Driven sprocket teeth", "T"), f("gearEfficiency", "ประสิทธิภาพเกียร์", "Gear efficiency", "η", .01), f("startupFactor", "ตัวคูณตอนสตาร์ท", "Startup factor", "SF", .1), f("serviceFactor", "ตัวคูณการใช้งาน", "Service factor", "SF", .1)],
  chain: [f("load", "น้ำหนักบรรทุก", "Payload", "kg"), f("length", "ระยะศูนย์กลาง", "Center distance", "m", .1), f("speed", "ความเร็วโซ่", "Chain speed", "m/min", .1), f("friction", "แรงเสียดทานกลิ้ง", "Rolling friction", "f", .01), f("movingMass", "มวลส่วนเคลื่อนที่", "Moving mass", "kg/m", .01), f("efficiency", "ประสิทธิภาพชุดขับ", "Drive efficiency", "η", .01), f("allowance", "แรงดึงที่ยอมได้", "Allowable load", "N"), f("sprocketDiameter", "เส้นผ่านศูนย์กลางพิทช์", "Sprocket pitch dia.", "mm", .1), f("loadFactor", "ตัวคูณโหลดเกียร์", "Gear load factor", "SF", .05)],
  bucket: [f("capacity", "กำลังลำเลียงที่ต้องการ", "Required capacity", "t/h", .1), f("density", "ความหนาแน่นวัสดุ", "Material density", "t/m³", .01), f("bucketVolume", "ปริมาตรบุ้งกี๋", "Bucket volume", "m³/pc", .0001), f("pitch", "พิทช์โซ่", "Chain pitch", "mm"), f("speed", "ความเร็วลำเลียง", "Conveying speed", "m/min", .1), f("height", "ความสูงลำเลียง", "Conveying height", "m", .1), f("bucketWeight", "น้ำหนักบุ้งกี๋", "Bucket weight", "kg/pc", .1), f("chainWeight", "น้ำหนักโซ่ต่อเส้น", "Chain / stand", "kg/m", .01), f("stands", "จำนวนเส้นโซ่", "Chain stands", "stand"), f("tempFactor", "ตัวคูณอุณหภูมิ", "Temperature factor", "SF", .1), f("operationFactor", "ตัวคูณการใช้งาน", "Operation factor", "SF", .1), f("averageStrength", "ความแข็งแรงเฉลี่ย", "Average strength", "kN", .1), f("efficiency", "ประสิทธิภาพมอเตอร์", "Motor efficiency", "η", .01)],
  screw: [f("screwDiameter", "เส้นผ่านศูนย์กลางสกรู", "Screw diameter", "m", .01), f("shaftDiameter", "เส้นผ่านศูนย์กลางเพลา", "Shaft diameter", "m", .01), f("pitch", "พิทช์สกรู", "Screw pitch", "m", .01), f("rpm", "รอบสกรู", "Revolution", "rpm", .1), f("filling", "อัตราการเติม", "Filling factor", "φ", .05), f("incline", "ตัวคูณความเอียง", "Incline factor", "K", .05), f("density", "ความหนาแน่นรวม", "Bulk density", "t/m³", .01), f("length", "ความยาวลำเลียง", "Conveyor length", "m", .1), f("friction", "แรงเสียดทานวัสดุ", "Material friction", "f", .1), f("height", "ความสูงลำเลียง", "Conveyor height", "m", .1), f("efficiency", "ประสิทธิภาพชุดขับ", "Drive efficiency", "η", .05)],
};

const finite = (v: number) => Number.isFinite(v) ? v : 0;
const format = (v: number, digits = 2) => new Intl.NumberFormat("th-TH", { maximumFractionDigits: digits }).format(finite(v));
const motorRatings = [.12, .18, .25, .37, .55, .75, 1.1, 1.5, 2.2, 3, 4, 5.5, 7.5, 11, 15, 18.5, 22, 30, 37, 45, 55, 75, 90];
const nextMotor = (kw: number) => motorRatings.find((rating) => rating >= kw) ?? Math.ceil(kw / 10) * 10;

function calculate(module: ModuleId, x: NumericFields, lang: Lang) {
  const T = (th: string, en: string) => tr([th, en], lang);
  if (module === "air") {
    const area = Math.PI * (x.bore / 10) ** 2 / 4, rodArea = Math.PI * (x.rod / 10) ** 2 / 4, speed = x.flow * 10000 / (area * 60);
    return { headline: [T("ความเร็วลูกสูบ", "Piston speed"), speed, "mm/s", 1] as const, metrics: [[T("พื้นที่ลูกสูบ", "Piston area"), area, "cm²", 2], [T("ความเร็ว", "Speed"), speed * 60 / 1000, "m/min", 2], [T("แรงดันออก", "Push force"), area * x.pressure * 1.019716213, "kgf", 1], [T("แรงดึงกลับ", "Pull force"), Math.max(area - rodArea, 0) * x.pressure * 1.019716213, "kgf", 1]] as const, formula: "v = Q × 10,000 ÷ (A × 60)", status: x.rod < x.bore ? T("พร้อมใช้งาน", "Ready") : T("ก้านต้องเล็กกว่ากระบอก", "Rod must be smaller than bore"), healthy: x.rod < x.bore };
  }
  if (module === "belt") {
    const volume = x.capacity / x.density, section = volume / (3600 * x.speed * x.slopeCoefficient), den = Math.tan(x.materialAngle / 3 * Math.PI / 180) + .75 * Math.tan(x.troughAngle * Math.PI / 180), minWidth = ((2 * Math.sqrt(section / den) + .05) / .9) * 1000, mass = volume * x.density * 1000 / (3600 * x.speed), power = (x.coefficient * x.friction * x.length * x.gravity * (mass + 5.375 + x.carryIdler / x.carryPitch) + x.coefficient * x.friction * x.length * x.gravity * (5.375 + x.returnIdler / x.returnPitch)) * x.speed / (1000 * x.efficiency);
    const recommendedWidth = standardBeltWidths.find((width) => width >= minWidth) ?? Math.ceil(minWidth / 200) * 200, widthMargin = x.selectedWidth - minWidth, selectedPasses = widthMargin >= 0;
    return { headline: [T("ความกว้างสายพานขั้นต่ำ", "Minimum belt width"), minWidth, "mm", 0] as const, metrics: [[T("ขนาดมาตรฐานที่แนะนำ", "Recommended standard width"), recommendedWidth, "mm", 0], [T("ระยะเผื่อของขนาดที่เลือก", "Selected width margin"), widthMargin, "mm", 0], [T("กำลังลำเลียงเชิงปริมาตร", "Volume capacity"), volume, "m³/h", 2], [T("กำลังชุดขับ", "Drive power"), power, "kW", 2], [T("ลูกกลิ้งขาไป", "Carrier rollers"), Math.ceil(x.length / x.carryPitch) + 1, "sets", 0], [T("ลูกกลิ้งขากลับ", "Return rollers"), Math.ceil(x.length / x.returnPitch) + 1, "sets", 0]] as const, formula: T("Bmin = ((2√(A ÷ (tan θ₁ + ¾ tan α))) + 0.05) ÷ 0.9\nBstandard = ขนาดมาตรฐานถัดไปที่ ≥ Bmin", "Bmin = ((2√(A ÷ (tan θ₁ + ¾ tan α))) + 0.05) ÷ 0.9\nBstandard = next standard width ≥ Bmin"), status: selectedPasses ? T(`สายพาน ${format(x.selectedWidth, 0)} mm ผ่าน (เผื่อ ${format(widthMargin, 0)} mm)`, `Selected ${format(x.selectedWidth, 0)} mm passes (${format(widthMargin, 0)} mm margin)`) : T(`ขนาด ${format(x.selectedWidth, 0)} mm แคบเกินไป · ใช้อย่างน้อย ${format(recommendedWidth, 0)} mm`, `Selected ${format(x.selectedWidth, 0)} mm is too narrow · use at least ${format(recommendedWidth, 0)} mm`), healthy: selectedPasses };
  }
  if (module === "flat") {
    const pitch = x.bagLength + x.gap, valid = pitch > 0 && x.length > 0 && x.pulleyDiameter > 0 && x.gearEfficiency > 0 && x.motorRpm > 0 && x.driveTeeth > 0 && x.drivenTeeth > 0 && x.gearboxRatio > 0;
    const requiredSpeed = valid ? x.throughput * pitch / 1000 / 60 : 0, speedMS = requiredSpeed / 60, requiredPulleyRpm = valid ? requiredSpeed / (Math.PI * x.pulleyDiameter / 1000) : 0, totalRatio = requiredPulleyRpm > 0 ? x.motorRpm / requiredPulleyRpm : 0, sprocketRatio = valid ? x.drivenTeeth / x.driveTeeth : 0, requiredGearboxRatio = sprocketRatio > 0 ? totalRatio / sprocketRatio : 0;
    const actualPulleyRpm = valid ? x.motorRpm / (x.gearboxRatio * sprocketRatio) : 0, actualSpeed = actualPulleyRpm * Math.PI * x.pulleyDiameter / 1000, actualCapacity = pitch > 0 ? actualSpeed * 60 * 1000 / pitch : 0, speedError = requiredSpeed > 0 ? (actualSpeed - requiredSpeed) / requiredSpeed * 100 : 0;
    const bags = valid ? Math.floor(x.length / pitch) : 0, mass = bags * x.bagWeight, rad = x.angle * Math.PI / 180, force = mass * 9.81 * (Math.cos(rad) * x.friction + Math.sin(rad)), requiredKw = valid ? force * speedMS * x.startupFactor * x.serviceFactor / x.gearEfficiency / 1000 : 0, selectedKw = nextMotor(requiredKw), torque = valid ? requiredKw * 1000 * 60 / (2 * Math.PI * x.motorRpm) : 0, speedOk = Math.abs(speedError) <= 5;
    return { headline: [T("มอเตอร์แนะนำ", "Recommended motor"), selectedKw, "kW", 2] as const, metrics: [[T("รอบพูลเลย์ที่ต้องการ", "Required pulley speed"), requiredPulleyRpm, "rpm", 2], [T("อัตราทดรวมที่ต้องการ", "Required total ratio"), totalRatio, ":1", 2], [T("อัตราทดเฟืองตาม/ขับ", "Driven/drive sprocket ratio"), sprocketRatio, ":1", 2], [T("อัตราทดเกียร์ที่ต้องการ", "Required gearbox ratio"), requiredGearboxRatio, ":1", 2], [T("รอบพูลเลย์จริง", "Actual pulley speed"), actualPulleyRpm, "rpm", 2], [T("ความเร็วสายพานจริง", "Actual belt speed"), actualSpeed, "m/min", 2], [T("อัตราการผลิตจริง", "Actual production rate"), actualCapacity, "bags/h", 0], [T("ความคลาดเคลื่อนความเร็ว", "Speed deviation"), speedError, "%", 2], [T("จำนวนกระสอบบนสายพาน", "Bags on belt"), bags, "bags", 0], [T("แรงบิดขั้นต่ำที่มอเตอร์", "Minimum motor torque"), torque, "N·m", 2]] as const, formula: "Pitch = Lbag + Gap\nvreq = Q × Pitch ÷ 1000 ÷ 60\nnpulley = vreq ÷ (π × Dpulley)\nisprocket = Zdriven ÷ Zdrive\nigearbox = (nmotor ÷ npulley) ÷ isprocket\nPmotor = Ftotal × vreq × SFstart × SFservice ÷ η", status: !valid ? T("กรุณาใส่ค่าที่มากกว่าศูนย์", "Enter values greater than zero") : speedOk ? T("อัตราทดที่เลือกให้ความเร็วอยู่ใน ±5%", "Selected ratio is within ±5% speed") : T("ควรปรับอัตราทดเกียร์ให้ใกล้ค่าที่ต้องการ", "Adjust gearbox ratio toward the required value"), healthy: valid && speedOk };
  }
  if (module === "chain") {
    const materialMass = x.load / x.length, tension = (materialMass * x.length * x.friction + x.movingMass * x.length * x.friction) * 9.81, maxTension = tension * x.speedFactor, power = maxTension / 1000 * x.speed / 60 * x.motorFactor / x.efficiency, rpm = x.speed / (Math.PI * x.sprocketDiameter / 1000), torque = 9550 * power / rpm * x.loadFactor;
    return { headline: [T("แรงดึงโซ่รวม", "Total chain tension"), maxTension, "N", 0] as const, metrics: [[T("กำลังที่ต้องการ", "Required power"), power, "kW", 3], [T("รอบสเตอร์", "Sprocket speed"), rpm, "rpm", 1], [T("แรงบิดออกแบบ", "Design torque"), torque, "N·m", 1], [T("การใช้โหลด", "Load utilization"), maxTension / x.allowance * 100, "%", 1]] as const, formula: "T = (M·L·f + m·L·f) × g", status: maxTension <= x.allowance ? T("โหลดโซ่ผ่าน", "Chain load passes") : T("โหลดโซ่เกินกำหนด", "Chain load exceeds limit"), healthy: maxTension <= x.allowance };
  }
  if (module === "bucket") {
    const volume = x.capacity / x.density, bucketsPerM = 1000 / x.pitch / 2, filling = volume / (x.bucketVolume * bucketsPerM * x.speed * 60), materialMass = x.capacity * 1000 / (x.speed * 60), t1 = materialMass * (x.height + 1) * 9.81 / 1000, t2 = x.bucketWeight * bucketsPerM * (x.height + 1) * 9.81 / 1000, t3 = x.chainWeight * x.stands * (x.height + 1) * 9.81 / 1000, selectTension = (t1 + t2 + t3) / x.stands * x.tempFactor * x.operationFactor, power = t1 * x.speed / 60 / x.efficiency * 1.1, sprocketDiameter = x.pitch / Math.sin(22.5 * Math.PI / 180) / 1000, links = Math.ceil(((x.height * 2 + sprocketDiameter * Math.PI) * x.stands * 1000 / x.pitch) / 4) * 4;
    return { headline: [T("กำลังมอเตอร์ที่ต้องการ", "Required motor power"), power, "kW", 2] as const, metrics: [[T("อัตราการเติม", "Filling"), filling * 100, "%", 1], [T("แรงดึงสำหรับเลือกโซ่", "Selection tension"), selectTension, "kN", 1], [T("จำนวนข้อโซ่", "Chain links"), links, "links", 0], [T("จำนวนบุ้งกี๋", "Buckets"), links / 4, "pcs", 0]] as const, formula: "P = T₁ × V ÷ 60 ÷ η × 1.1", status: x.averageStrength >= selectTension ? T("โซ่ที่เลือกผ่าน", "Selected chain passes") : T("โซ่ที่เลือกไม่ผ่าน", "Selected chain fails"), healthy: x.averageStrength >= selectTension };
  }
  const area = Math.PI / 4 * (x.screwDiameter ** 2 - x.shaftDiameter ** 2), volume = 60 * area * x.pitch * x.rpm * x.filling * x.incline, normal = volume * x.density, max = normal / x.filling, power = max * 9.81 * (x.length * x.friction + x.height) / 3600 / x.efficiency, inner = Math.max(x.pipeOD - 2 * x.pipeThickness, 0), inertia = Math.PI / 64 * (x.pipeOD ** 4 - inner ** 4), weight = Math.PI / 4 * (x.pipeOD ** 2 - inner ** 2) * x.pipeLength * 7850 / 1e9, deflection = 5 * weight * 9.81 * x.pipeLength ** 3 / (384 * x.elasticModulus * inertia), limit = x.pipeLength / 1000;
  return { headline: [T("กำลังลำเลียงสูงสุด", "Maximum capacity"), max, "t/h", 4] as const, metrics: [[T("กำลังลำเลียงปกติ", "Normal capacity"), normal, "t/h", 4], [T("กำลังมอเตอร์", "Motor power"), power, "kW", 4], [T("การโก่งตัวของเพลา", "Pipe deflection"), deflection, "mm", 3], [T("ค่าการโก่งตัวที่ยอมได้", "Deflection limit"), limit, "mm", 2]] as const, formula: "Q = 60 × π/4 × (D² − d²) × S × N × φ × K", status: deflection <= limit ? T("การโก่งตัวผ่าน", "Shaft deflection passes") : T("การโก่งตัวไม่ผ่าน", "Shaft deflection fails"), healthy: deflection <= limit };
}

const ui: Record<string, Bi> = {
  verified: ["ตรวจสอบสูตรแล้ว", "Formula verified"], install: ["ดาวน์โหลดแอป", "Download App"], eyebrow: ["เครื่องคำนวณวิศวกรรม · REV 05", "ENGINEERING CALCULATOR · REV 05"], title1: ["คำนวณงานวิศวกรรม", "Engineering math,"], title2: ["ชัดเจนในทุกขั้นตอน", "beautifully clear."], intro: ["เครื่องมือคำนวณระบบลำเลียงและนิวเมติก พร้อมหน่วย สูตร และผลลัพธ์ที่ตรวจสอบย้อนกลับได้", "Verified conveyor and pneumatic calculators with traceable units, formulas, and live results."], calculators: ["6 เครื่องคำนวณ", "6 calculators"], live: ["ผลลัพธ์ทันที", "Live results"], units: ["หน่วย SI", "SI units"], inputs: ["ข้อมูลนำเข้า", "INPUTS"], reset: ["ค่าเริ่มต้น", "Reset"], results: ["ผลการคำนวณ", "CALCULATION RESULTS"], formula: ["สูตรที่ใช้", "Formula used"], note: ["รายงาน PDF จะรวมข้อมูลนำเข้า ผลลัพธ์ และสูตรนี้", "The PDF report includes inputs, results, and this formula."], export: ["ส่งออก PDF", "Export PDF"], copy: ["คัดลอกผลลัพธ์", "Copy results"], copied: ["คัดลอกแล้ว ✓", "Copied ✓"], report: ["รายงานการคำนวณ CalFlow", "CalFlow calculation report"],
};

export default function Home() {
  const [active, setActive] = useState<ModuleId>("flat"), [lang, setLang] = useState<Lang>("th"), [inputs, setInputs] = useState<Record<ModuleId, NumericFields>>(defaults), [copied, setCopied] = useState(false), [installPrompt, setInstallPrompt] = useState<InstallPromptEvent | null>(null);
  const result = useMemo(() => calculate(active, inputs[active], lang), [active, inputs, lang]), current = modules.find((item) => item.id === active)!;
  const [headlineLabel, headlineValue, headlineUnit, headlineDigits] = result.headline;
  const U = (key: string) => tr(ui[key], lang);
  const update = (key: string, value: string) => setInputs((state) => ({ ...state, [active]: { ...state[active], [key]: Number(value) } }));
  const copySummary = async () => { const lines = [`${tr(current.label, lang)} — ${result.status}`, `${headlineLabel}: ${format(headlineValue, headlineDigits)} ${headlineUnit}`, ...result.metrics.map(([label, value, unit, digits]) => `${label}: ${format(value, digits)} ${unit}`), "", U("formula"), result.formula]; await navigator.clipboard.writeText(lines.join("\n")); setCopied(true); window.setTimeout(() => setCopied(false), 1600); };
  const exportPdf = () => { const previous = document.title; document.title = `CalFlow - ${tr(current.label, lang)}`; window.print(); window.setTimeout(() => { document.title = previous; }, 300); };
  useEffect(() => {
    if ("serviceWorker" in navigator) navigator.serviceWorker.register(new URL("sw.js", window.location.href).pathname).catch(() => undefined);
    const capture = (event: Event) => { event.preventDefault(); setInstallPrompt(event as InstallPromptEvent); };
    window.addEventListener("beforeinstallprompt", capture);
    return () => window.removeEventListener("beforeinstallprompt", capture);
  }, []);
  const installApp = async () => {
    if (installPrompt) { await installPrompt.prompt(); await installPrompt.userChoice; setInstallPrompt(null); return; }
    window.alert(lang === "th" ? "iPhone/iPad: เปิดเว็บนี้ใน Safari แล้วแตะ แชร์ → เพิ่มไปยังหน้าจอโฮม\n\nคอมพิวเตอร์/Android: เปิดด้วย Chrome หรือ Edge แล้วเลือก Install app" : "iPhone/iPad: Open this site in Safari, then tap Share → Add to Home Screen.\n\nDesktop/Android: Open in Chrome or Edge and choose Install app.");
  };

  return <main><div className="ambient ambient-one" /><div className="ambient ambient-two" />
    <header className="topbar"><a className="brand" href="#top"><span className="brand-mark">C</span><span>CalFlow</span></a><div className="top-actions"><button className="install-button" onClick={installApp}>↓ <span>{U("install")}</span></button><div className="language-switch"><button className={lang === "th" ? "active" : ""} onClick={() => setLang("th")}>TH</button><button className={lang === "en" ? "active" : ""} onClick={() => setLang("en")}>EN</button></div><div className="topbar-meta"><span className="live-dot" />{U("verified")}</div></div></header>
    <section className="hero" id="top"><div className="eyebrow">{U("eyebrow")}</div><h1>{U("title1")}<br /><span>{U("title2")}</span></h1><p>{U("intro")}</p><div className="hero-chips"><span>{U("calculators")}</span><span>{U("live")}</span><span>{U("units")}</span></div></section>
    <nav className="module-dock">{modules.map((item) => <button key={item.id} className={active === item.id ? "module-button active" : "module-button"} onClick={() => setActive(item.id)}><span className="module-symbol">{item.symbol}</span><span><strong>{tr(item.label, lang)}</strong><small>{tr(item.short, lang)}</small></span></button>)}</nav>
    <div className="print-title"><strong>{U("report")}</strong><span>{tr(current.label, lang)}</span></div>
    <section className="workspace" aria-live="polite"><div className="input-panel glass-card"><div className="panel-heading"><div><span className="section-kicker">{U("inputs")}</span><h2>{tr(current.label, lang)}</h2></div><button className="text-button no-print" onClick={() => setInputs((state) => ({ ...state, [active]: { ...defaults[active] } }))}>{U("reset")}</button></div><div className="input-grid">{fieldConfig[active].map((field) => <label className="field" key={field.key}><span>{tr(field.label, lang)}</span><div className="field-control">{field.options ? <select aria-label={tr(field.label, lang)} value={inputs[active][field.key]} onChange={(event) => update(field.key, event.target.value)}>{field.options.map((option) => <option value={option} key={option}>{format(option, 0)}</option>)}</select> : <input aria-label={tr(field.label, lang)} type="number" step={field.step ?? 1} value={inputs[active][field.key]} onChange={(event) => update(field.key, event.target.value)} />}<em>{field.unit}</em></div></label>)}</div></div>
      <aside className="result-panel glass-card"><div className="result-header"><div><span className="section-kicker">{U("results")}</span><h2>{tr(current.label, lang)}</h2></div><span className="result-symbol">{current.symbol}</span></div><p className="result-label">{headlineLabel}</p><div className="hero-result"><strong>{format(headlineValue, headlineDigits)}</strong><span>{headlineUnit}</span></div><div className={result.healthy ? "status-pill good" : "status-pill warning"}><i />{result.status}</div><div className="metric-list">{result.metrics.map(([label, value, unit, digits]) => <div className="metric-row" key={label}><span>{label}</span><strong>{format(value, digits)} <small>{unit}</small></strong></div>)}</div><div className="formula-card"><span>{U("formula")}</span><code>{result.formula}</code><p>{U("note")}</p></div><div className="result-actions no-print"><button className="secondary-button" onClick={copySummary}>{copied ? U("copied") : U("copy")}</button><button className="primary-button" onClick={exportPdf}>{U("export")} ↓</button></div></aside></section>
    <section className="trust-strip"><div><strong>{lang === "th" ? "หน่วยถูกต้อง" : "Correct units"}</strong><span>SI conversion</span></div><div><strong>{lang === "th" ? "ตรวจสอบย้อนกลับ" : "Traceable logic"}</strong><span>{lang === "th" ? "แสดงสูตรในรายงาน" : "Formulas included in reports"}</span></div><div><strong>{lang === "th" ? "รองรับสองภาษา" : "Bilingual"}</strong><span>ไทย / English</span></div></section><footer><span>CalFlow Engineering Toolkit</span><span>Verified workbook logic · 2026</span></footer>
  </main>;
}
